mode: 'staging'
server:
  port: 3015
header:
  auth_token_key: 'Authorization'
mongodb:
  uris: 'mongodb+srv://tms_demo_user:583OAjk0vyFLGmFg@cluster0.pifwjqj.mongodb.net/TMS?retryWrites=true&w=majority&appName=Cluster0'
  options: {}
log:
  enable: true
  level: 'error'
  exception:
    enable: true
    dir: 'logs'
    filename: 'uncaughtExceptions.log'
    path: 'logs/uncaughtExceptions.log'
    level: 'error'
  rejection:
    enable: true
  logging:
    enable: true
    dir: 'logs'
    filename: 'logfile.log'
    path: 'logs/logfile.log'
    level: 'info'
routes:
  request:
    raw:
      enable: true
      options:
        limit: '100mb'
    form_urlencoded:
      enable: true
      urlencoded_options:
        limit: '100mb'
        extended: true
      options:
        limit: '100mb'
  cors_root: 
    check: false
    origin: [
      '<add your domin>',
      'localhost:3015'
    ]
    options: 
      Vary: 'Origin'
      origin: '<add your domain>'
      methods: 'GET,PUT,POST,DELETE'
      preflightContinue: false
      optionsSuccessStatus: 204
  cors:
    origin: '*'
    methods: 'GET,PUT,POST,DELETE'
    preflightContinue: false
    optionsSuccessStatus: 204
gateway_auth: 
  secret: 'HJum9R5JZfzbb7C7ac59wmlQ8TrwdZAjX6n7JnJdzyBidPZ9LAo59Yhj091pt11r'
  auth_token_key: 'Authorization'
  jwt:
    expiresIn: '24h'
swagger:
  enable: true
  users: [
    'DemoUser'
  ]
  auth_key: 'DemoPass' 
socket:
  path: '/tms'